services:
  - type: web
    name: attendance-system
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/Attendance-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: DATABASE_URL
        fromDatabase:
          name: attendance-db
          property: connectionString
      - key: PGUSER
        fromDatabase:
          name: attendance-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: attendance-db
          property: password
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: attendance-db
    plan: free
    databaseName: attendance_db
